### ISSUE TITLE
HTTP header based token error

### ISSUE THREAD

**Issue by roirodriguez** [chameleonbr/node-red-contrib-jwt#7]
Hello,

We are getting the following error when using bearer (header) based tokens:

`{"message":"TypeError: Cannot read property 'header' of null","source":{"id":"816f695f.19d66","type":"jwt verify","name":"","count":1},"stack":"TypeError: Cannot read property 'header' of null\n    at GetTokenHeader (/data/node_modules/node-red-contrib-jwt/jwt.js:166:21)\n    at JwtVerify.<anonymous> (/data/node_modules/node-red-contrib-jwt/jwt.js:103:30)\n    at JwtVerify.emit (events.js:189:13)\n    at JwtVerify.Node.receive (/root/.nvm/versions/node/v10.15.3/lib/node_modules/node-red/node_modules/@node-red/runtime/lib/nodes/Node.js:237:14)\n    at HTTPIn.Node.send (/root/.nvm/versions/node/v10.15.3/lib/node_modules/node-red/node_modules/@node-red/runtime/lib/nodes/Node.js:159:22)\n    at HTTPIn.callback (/root/.nvm/versions/node/v10.15.3/lib/node_modules/node-red/node_modules/@node-red/nodes/core/io/21-httpin.js:199:26)\n    at Layer.handle [as handle_request] (/root/.nvm/versions/node/v10.15.3/lib/node_modules/node-red/node_modules/express/lib/router/layer.js:95:5)\n    at next (/root/.nvm/versions/node/v10.15.3/lib/node_modules/node-red/node_modules/express/lib/router/route.js:137:13)\n    at metricsHandler (/root/.nvm/versions/no..."}`

This happens when the authorization header have 'bearer' spelled all in lower case. From line 83 at jwt.js onwards:

```
        node.on('input', function (msg) {
            if (node.signvar === 'bearer') {
                if (msg.req !== undefined && msg.req.get('authorization') !== undefined) {
                    var authz = msg.req.get('authorization').split(' ');
                    if(authz.length == 2 && authz[0] === 'Bearer'){
                        msg.bearer = authz[1];
                   }
                } else if (msg.req.query.access_token !== undefined) {
                    msg.bearer = msg.req.query.access_token;
                } else if (msg.req.body !== undefined && msg.req.body.access_token !== undefined) {
                    msg.bearer = msg.req.body.access_token;
                }
}

I would suggest substituting that _authz[0] === 'Bearer'_ by _'bearer' === authz[0].toLowerCase()_.

May i PR or something?
```

**Comment by roirodriguez** [comment]
I've checked the RFC (https://tools.ietf.org/html/rfc6750#section-2.1) and it seems that Bearer should be spelled like that, with a capital 'B'. I'm not completely sure of this, as i didn't found anywhere in there telling explicitly if that specification is case sensitive or not (i didn't read that deeply).

So the problem in my case is the 'keycloack-angular' lib, which generates that all in lowercase. I don't know how many software out there would misspell this.

I'm posting this for you to know and be able to take a proper decision. 
Cheers.

**Comment by chameleonbr** [comment]
Hi, in all of documentation and libs I see Bearer token with capital B, but if you need other prefix now pass msg.prefix to jwt node and the node will verify with your prefix.
